# human wilcox
nohup /home/zoo/ball6395/software/miniconda3/envs/sc/bin/Rscript /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Ohnologs_stats.v2.R -I /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Hsap_background_genes.txt -P /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/03.ohnolog_identification/Ohnologs-v2.0/7_FilterOhnologs/Hsap.ohnologs.txt -M /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/01.data/03.markers/Hsap_lung/Hsap_lung.wilcox.FDR001.coding_genes.txt  -S Hsap_lung -O Hsap_lung  &
nohup /home/zoo/ball6395/software/miniconda3/envs/sc/bin/Rscript /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Paralogs_stats.v2.R -I /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Hsap_background_genes.txt -P /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/03.paralog_inferring/Hsap.paralogs.txt -M /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/01.data/03.markers/Hsap_lung/Hsap_lung.wilcox.FDR001.coding_genes.txt -S Hsap_lung -O Hsap_lung &
nohup /home/zoo/ball6395/software/miniconda3/envs/sc/bin/Rscript /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/non_Ohnolog_Paralogs_stats.v2.R -I /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Hsap_background_genes.txt -P1 /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/03.paralog_inferring/Hsap.paralogs.txt -P2 /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/03.ohnolog_identification/Ohnologs-v2.0/7_FilterOhnologs/Hsap.ohnologs.txt -M  /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/01.data/03.markers/Hsap_lung/Hsap_lung.wilcox.FDR001.coding_genes.txt -S Hsap_lung -O Hsap_lung &


# human wilcox
nohup /home/zoo/ball6395/software/miniconda3/envs/sc/bin/Rscript /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Ohnologs_stats.v2.R -I /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Hsap_background_genes.txt -P /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/03.ohnolog_identification/Ohnologs-v2.0/7_FilterOhnologs/Hsap.ohnologs.txt -M /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/01.data/03.markers/Hsap_eye/Hsap_eye.wilcox.FDR001.coding_genes.txt  -S Hsap_eye -O Hsap_eye  &
nohup /home/zoo/ball6395/software/miniconda3/envs/sc/bin/Rscript /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Paralogs_stats.v2.R -I /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Hsap_background_genes.txt -P /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/03.paralog_inferring/Hsap.paralogs.txt -M /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/01.data/03.markers/Hsap_eye/Hsap_eye.wilcox.FDR001.coding_genes.txt -S Hsap_eye -O Hsap_eye &
nohup /home/zoo/ball6395/software/miniconda3/envs/sc/bin/Rscript /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/non_Ohnolog_Paralogs_stats.v2.R -I /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/04.ohno_para_significance/0bin/Hsap_background_genes.txt -P1 /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/03.paralog_inferring/Hsap.paralogs.txt -P2 /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/03.ohnolog_identification/Ohnologs-v2.0/7_FilterOhnologs/Hsap.ohnologs.txt -M  /mnt/data01/yuanzhen/01.Vertebrate_cell_evo/01.data/03.markers/Hsap_eye/Hsap_eye.wilcox.FDR001.coding_genes.txt -S Hsap_eye -O Hsap_eye &


